// custom-components/react-carousel/carousel.jsx
const newId = (() => {
  let uid = 0
  return () => uid++
})()

function Product(props) {
  const {Deeplink, ImageURL, Price, Title} = props.record
  return (
    <a href={Deeplink} className="product">
      <img src={ImageURL} alt={Title} />
      <div className="title">{Title}</div>
      <div className="price">{Price}</div>
    </a>
  )
}

function Carousel(props) {
  const uid = newId()
  const ref = React.useRef()
  const [offset, setOffset] = React.useState(0)
  const [records, setRecords] = React.useState([])

  React.useEffect(() => {
    let subscriptionKey = '';

    (async () => {
      const {EventAggregator, ResultDispatcher} = (await withFactfinder()).communication

      setTimeout(() => EventAggregator.addFFEvent({
        type: 'search',
        query: props.query,
        topics: () => ['carousel-' + uid]
      }))

      subscriptionKey = ResultDispatcher.subscribe('carousel-' + uid, ({searchResult}) => {
        setRecords(searchResult.records.map(r => r.record))
      })
    })()

    return async () => {
      const {ResultDispatcher} = (await withFactfinder()).communication
      ResultDispatcher.unsubscribe('carousel-' + uid, subscriptionKey)
    }
  }, [props.query])

  const prev = () => setOffset((offset - 4 + records.length) % records.length)

  const next = () => setOffset((offset + 4) % records.length)

  const transformStyles = () => {
    const products = ref.current ? ref.current.querySelectorAll('.product') : []
    if (products.length) {
      const offsetPx = products[offset].offsetLeft - products[0].offsetLeft
      return {transform: 'translateX(-' + offsetPx + 'px)'}
    }
    return {}
  }

  return (
    <div className={'carousel-wrapper ' + props.className} ref={ref}>
      <div className="button prev-button" onClick={prev}>❮</div>
      <div className="carousel" style={transformStyles()}>
        {records.map(r => <Product record={r} key={r.ArticleID} />)}
      </div>
      <div className="button next-button" onClick={next}>❯</div>
    </div>
  )
}

function withFactfinder() {
  return new Promise(resolve => {
    if (typeof window.factfinder !== 'undefined') {
      resolve(window.factfinder)
    } else {
      document.addEventListener('ffReady', (event) => {
        resolve(event.factfinder)
      })
    }
  })
}

function App() {
  return (
    <React.Fragment>
      <Carousel query="hat" className="hats-carousel" />
      <ff-record-list unresolved>
        <ff-record>
          <a data-anchor="{{record.Deeplink}}" className="product">
            <img alt="{{record.Title}}" data-image="{{record.ImageURL}}" />
            <div className="title">{"{{record.Title}}"}</div>
            <div className="price">{"{{record.Price}}"}</div>
          </a>
        </ff-record>
      </ff-record-list>
      <Carousel query="shoe" className="shoes-carousel" />
    </React.Fragment>
  )
}

ReactDOM.render(<App />, document.getElementById('app'))

// custom-components/angular-carousel/src/app/carousel/carousel.component.ts
import {Component, ElementRef, Input, OnDestroy, OnInit, QueryList, ViewChildren} from '@angular/core';

import {ProductComponent} from '../product/product.component';
import {Record} from '../record.interface';

let UID: number = 0;
function newId() {
    return UID++;
}

@Component({
    selector: 'ffc-carousel',
    host: {class: 'carousel-wrapper'},
    template: `
        <div (click)="prev()" class="button prev-button">❮</div>
        <div [ngStyle]="transformStyles" class="carousel">
            <ffc-product *ngFor="let record of records" [record]="record"></ffc-product>
        </div>
        <div (click)="next()" class="button next-button">❯</div>
    `,
    styles: []
})
export class CarouselComponent implements OnInit, OnDestroy {
    records: Record[] = [];

    @Input()
    private query: string;

    @ViewChildren(ProductComponent, {read: ElementRef})
    private productComponents: QueryList<ElementRef>;

    private subscriptionKey: string;
    private uid: number = newId();
    private offset: number = 0;

    constructor(private el: ElementRef) {
    }

    ngOnInit(): void {
        awaitFactfinder((resultDispatcher, eventAggregator) => {
            setTimeout(() => {
                // trigger search on a dedicated topic
                eventAggregator.addFFEvent({
                    type: 'search',
                    query: this.query,
                    topics: () => [`carousel-${this.uid}`]
                });
            });

            // update component's data when FACT-Finder response comes
            this.subscriptionKey = resultDispatcher.subscribe(`carousel-${this.uid}`, response => {
                this.records = response.searchResult.records.map(record => record.record);
            });
        });
    }

    ngOnDestroy(): void {
        awaitFactfinder(resultDispatcher => {
            if (this.subscriptionKey) {
                resultDispatcher.unsubscribe(`carousel-${this.uid}`, this.subscriptionKey);
            }
        });
    }

    next(): void {
        this.offset = (this.offset + 4) % this.records.length;
    }

    prev(): void {
        this.offset = (this.offset - 4 + this.records.length) % this.records.length;
    }

    get transformStyles(): {transform?: string;} {
        if (!this.productComponents) {
            return {};
        }

        const products: ElementRef[] = this.productComponents.toArray();
        if (products.length === 0) {
            return {};
        }

        const offsetPx: number = products[this.offset].nativeElement.offsetLeft - products[0].nativeElement.offsetLeft;
        return {transform: `translateX(-${offsetPx}px)`};
    }
}

function awaitFactfinder(callback) {
    const factfinder = (<any>window).factfinder;
    if (factfinder) {
        callback(factfinder.communication.ResultDispatcher, factfinder.communication.EventAggregator);
    } else {
        // @ts-ignore
        document.addEventListener('ffReady', ({resultDispatcher, eventAggregator}) => callback(resultDispatcher, eventAggregator));
    }
}
